### ISSUE TITLE
Review and complete README documentation with the latest changes

### ISSUE THREAD

**Issue by gabipetrovay** [jxmono/login#14]
Please make a review of the README documentation. (Feel free to improve/restructure it where necessary)

Add the missing documentation for:
- [`customReceiverHandler`](https://github.com/jillix/login/commit/e35eefaf00082495e719a0fdf84d5d4aec72fd23)
- [`templateFile`](https://github.com/jillix/login/commit/0d4a2ff3d10102dcb4e208d2ea218a0617fb7328)

Please make the changes in the [forgotCustomCode-event](https://github.com/jillix/login/tree/forgotCustomCode-event) branch.

**Comment by danandrei** [comment]
Done in https://github.com/jillix/login/commit/6fedf81fd2d1461e280874171e9142a13a0c2f38
